apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv1
  labels:
    type: local
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Recycle ## Retain / Delete
  capacity:
    storage: 1000Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /dbdata
