apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc1
spec:
  storageClassName: standard
  volumeName: my-pv1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
